stackname: covidgeneric
env_folder: env_vars
replicas:
  dev: 1
  qa: 1 
  uat: 1
  prod: 3
restart_policy: any
max_mem: 1024M
max_cpu: 1
traefik_application_port: 8000
traefik_https_enable: true
traefik_ssl_provider: letsencrypt
vault:
  enabled: true
  name: civicsense_students_admin_fe
  envs:
    - AUTH_HEADER
    - HQIMS_AUTH_HEADER
    - AGENT_ADMIN_API_URL
    - HQIMS_API_URL
    - REACT_APP_GOOGLE_KEY
    - APP_TITLE
    - IS_GCC
