export default {
  ACCEPT_OR_REJECT_ENTRIES: 'ACCEPT_OR_REJECT_ENTRIES',
  ACCEPT_OR_REJECT_ENTRIES_SUCCESS: 'ACCEPT_OR_REJECT_ENTRIES_SUCCESS',
  ACCEPT_OR_REJECT_ENTRIES_FAILURE: 'ACCEPT_OR_REJECT_ENTRIES_FAILURE',
};
