export default {
  GET_ALL_CAMPAIGNS_LIST: 'GET_ALL_CAMPAIGNS_LIST',
  GET_ALL_CAMPAIGNS_LIST_SUCCESS: 'GET_ALL_CAMPAIGNS_LIST_SUCCESS',
  GET_ALL_CAMPAIGNS_LIST_FAILURE: 'GET_ALL_CAMPAIGNS_LIST_FAILURE',
};
