export default {
  GET_ALL_ENTRIES: 'GET_ALL_ENTRIES',
  GET_ALL_ENTRIES_SUCCESS: 'GET_ALL_ENTRIES_SUCCESS',
  GET_ALL_ENTRIES_FAILURE: 'GET_ALL_ENTRIES_FAILURE',
  CLEAR_ALL_ENTRIES: 'CLEAR_ALL_ENTRIES'
};
