export default {
  GET_CAMPAIGN_DETAILS: 'GET_CAMPAIGN_DETAILS',
  GET_CAMPAIGN_DETAILS_SUCCESS: 'GET_CAMPAIGN_DETAILS_SUCCESS',
  GET_CAMPAIGN_DETAILS_FAILURE: 'GET_CAMPAIGN_DETAILS_FAILURE',
  CLEAR_CAMPAIGN_ENTRIES: 'CLEAR_CAMPAIGN_ENTRIES',
};
