export const getConfigUrl = '/api/config';
export const adminLoginUrl = '/api/csr/admin/login';
export const getAllCampaignsUrl = '/api/csr/campaigns?live=false';
export const getACampaignDetails = '/api/csr/campaigns/';
export const getImageUrl = '/api/csr/images/';
export const fetchLocationURL = '/api/csr/location';
export const createCampaignURL = '/api/csr/campaigns';
export const approveOrRejectEntriesURL = '/api/csr/submission/';
export const getOTPUrl = 'api/csr/user/generate-otp';
export const getReportsUrl = 'api/csr/reports';
export const getPositiveEntriesUrl = 'api/csr/positive-reports?status=OPEN';
export const getHotZonesUrl = '/api/csr/hotspots';
export const getTestingCentersUrl = '/api/csr/testingCenters';
export const getHealthCentersUrl = '/api/csr/healthCenters';
export const reportsFileFromServerUrl = '/api/csr/v2/reports?download=true'
